# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_auto_20170616_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pas',
            new_name='password',
        ),
    ]
