# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_remove_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.BooleanField(default=True),
        ),
    ]
