# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_auto_20170703_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.BooleanField(),
        ),
    ]
