# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0011_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='product_name',
            new_name='variation_name',
        ),
    ]
