# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0012_auto_20170703_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='products/img/'),
        ),
    ]
