# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0013_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='myshop/products/img/'),
        ),
    ]
