# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0016_auto_20170704_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, unique=True),
        ),
    ]
