# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0018_auto_20170704_0612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-product_name']},
        ),
    ]
