# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0020_productfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='make_image_background',
            field=models.BooleanField(default=False),
        ),
    ]
