# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0021_productfeature_make_image_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
