# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0026_auto_20170704_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='line_item_total',
            field=models.DecimalField(decimal_places=2, default=1699, max_digits=10),
            preserve_default=False,
        ),
    ]
