# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0028_cart_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='line_item_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
