# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0030_auto_20170705_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='line_item_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
