# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0032_auto_20170705_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='taxtotal',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
    ]
