# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0033_auto_20170705_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.085, max_digits=50),
        ),
    ]
