# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0037_usercheckout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercheckout',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserCheckout',
        ),
    ]
