# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0040_auto_20170705_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
    ]
