# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0041_remove_order_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_no',
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_no',
            field=models.IntegerField(),
        ),
    ]
