# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0042_auto_20170705_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='order_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
