# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0044_auto_20170705_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.IntegerField(max_length=7, null=True),
        ),
    ]
