# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0045_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_no',
            field=models.IntegerField(unique=False),
        ),
    ]
