# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0046_auto_20170706_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_no',
        ),
    ]
