# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0047_remove_order_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
