# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0049_auto_20170706_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(default='pending', max_length=20)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('invoice_no', models.IntegerField(unique=True)),
                ('total_products', models.IntegerField(max_length=5)),
                ('cart', models.IntegerField(max_length=7, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='order_id_order_details', serialize=False, to='myshop.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_id_payment', to='myshop.Order'),
            preserve_default=False,
        ),
    ]
