# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-30 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0050_auto_20170706_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinoCredit',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('credit', models.FloatField(max_length=20)),
                ('used', models.FloatField(max_length=20)),
            ],
        ),
    ]
